FROM python353-centos7:latest
MAINTAINER yunding-sa <tech@go.cc>

ARG PROJECT_NAME="FastDevops"
ARG SUPERVISOR_CONFIG="FastDevops.conf"

#COPY ./${PROJECT_NAME} /data/wwwroot/${PROJECT_NAME}
COPY ./${SUPERVISOR_CONFIG} /etc/supervisor/conf.d/${SUPERVISOR_CONFIG}
COPY ./requirements /requirements
RUN pip install -r /requirements
EXPOSE 9000
ENTRYPOINT ['python36','/data/wwwroot/FastDevops/manage.py','runserver','0.0.0.0:9000']
